data:
  dataset:
    name: BratsProcessednNative
    samples: 1036
    type: private
  datasetLoadOption: batch
  kfold: 1
  mapping:
    Filename:
      options:
        Augmentation: true
        Height: '128'
        Normalization: false
        Resize: true
        Scaling: 1
        Width: '128'
        height_shift_range: 0
        horizontal_flip: false
        pretrained: InceptionV3
        rotation_range: 0
        shear_range: 0
        vertical_flip: false
        width_shift_range: 0
      port: InputPort0,OutputPort0
      shape: ''
      type: Image
    Label:
      options: {}
      port: ''
      shape: ''
      type: Categorical
  numPorts: 1
  samples:
    split: 5
    test: 51
    training: 932
    validation: 51
  shuffle: false
model:
  connections:
  - source: MaxPooling2D_32
    target: Conv2D_118
  - source: Conv2D_117
    target: MaxPooling2D_32
  - source: Conv2D_109
    target: Conv2D_110
  - source: Conv2D_108
    target: Conv2D_109
  - source: Conv2D_120
    target: Conv2D_121
  - source: Conv2D_112
    target: Conv2D_113
  - source: UpSampling2D_7
    target: Conv2D_108
  - source: Conv2D_113
    target: Conv2D_114
  - source: Input_11
    target: UpSampling2D_6
  - source: Conv2D_116
    target: Conv2D_117
  - source: Conv2D_121
    target: Output_31
  - source: Conv2D_111
    target: Conv2D_112
  - source: Conv2D_114
    target: Conv2D_115
  - source: UpSampling2D_6
    target: Conv2D_107
  - source: Conv2D_118
    target: Conv2D_119
  - source: Conv2D_119
    target: Conv2D_120
  - source: Conv2D_110
    target: Conv2D_111
  - source: Conv2D_107
    target: UpSampling2D_7
  - source: Conv2D_115
    target: Conv2D_116
  layers:
  - args: {}
    class: Output
    name: Output_31
    x: 833
    y: 844
  - args: {}
    class: Input
    name: Input_11
    x: 61
    y: 239
  - args: {}
    class: UpSampling2D
    name: UpSampling2D_6
    x: 61
    y: 362
  - args:
      filters: '3'
      kernel_size: (1,1)
    class: Conv2D
    name: Conv2D_107
    x: 61
    y: 482
  - args: {}
    class: UpSampling2D
    name: UpSampling2D_7
    x: 61
    y: 602
  - args:
      filters: '3'
      kernel_size: (1,1)
    class: Conv2D
    name: Conv2D_108
    x: 61
    y: 721
  - args:
      dilation_rate: '6'
      filters: '3'
      kernel_size: (3,1)
      use_bias: false
    class: Conv2D
    name: Conv2D_109
    x: 423
    y: 61
  - args:
      dilation_rate: '6'
      filters: '3'
      kernel_size: (1,3)
      use_bias: false
    class: Conv2D
    name: Conv2D_110
    x: 423
    y: 180
  - args:
      activation: softmax
      dilation_rate: '12'
      filters: '3'
      kernel_size: (3,1)
    class: Conv2D
    name: Conv2D_111
    x: 423
    y: 301
  - args:
      dilation_rate: '12'
      filters: '3'
      kernel_size: (1,3)
    class: Conv2D
    name: Conv2D_112
    x: 423
    y: 421
  - args:
      dilation_rate: '18'
      filters: '3'
      kernel_size: (3,1)
      use_bias: false
    class: Conv2D
    name: Conv2D_113
    x: 423
    y: 540
  - args:
      dilation_rate: '18'
      filters: '3'
      kernel_size: (1,3)
    class: Conv2D
    name: Conv2D_114
    x: 423
    y: 663
  - args:
      dilation_rate: '24'
      filters: '3'
      kernel_size: (1,3)
    class: Conv2D
    name: Conv2D_115
    x: 423
    y: 784
  - args:
      dilation_rate: '24'
      filters: '3'
      kernel_size: (3,1)
    class: Conv2D
    name: Conv2D_116
    x: 423
    y: 902
  - args:
      filters: '3'
      kernel_size: (1,1)
    class: Conv2D
    name: Conv2D_117
    x: 833
    y: 121
  - args: {}
    class: MaxPooling2D
    name: MaxPooling2D_32
    x: 833
    y: 244
  - args:
      activation: softmax
      dilation_rate: '2'
      filters: '3'
      kernel_size: (16,16)
      use_bias: false
    class: Conv2D
    name: Conv2D_118
    x: 833
    y: 366
  - args:
      dilation_rate: '2'
      filters: '3'
      kernel_size: (16,16)
      use_bias: false
    class: Conv2D
    name: Conv2D_119
    x: 833
    y: 483
  - args:
      dilation_rate: (1,1)
      filters: '3'
      kernel_size: (8, 8)
    class: Conv2D
    name: Conv2D_120
    x: 833
    y: 604
  - args:
      filters: '3'
      kernel_size: (2,2)
    class: Conv2D
    name: Conv2D_121
    x: 833
    y: 725
params:
  advance_params: true
  batch_size: 32
  is_custom_loss: false
  loss_func: categorical_crossentropy
  num_epoch: 100
  optimizer:
    name: Adadelta
project: Neuroimaging
